### ISSUE TITLE
Error on kali Linux App

### ISSUE THREAD

**Issue by alishahaan** [imperva/automatic-api-attack-tool#2]
I got an error while running this command 

> api-attack.sh -f swaggerPetStore.json -n myapisite.com -s http -rcn=403

**Error:** Could not find or load main class **com.imperva.apiattacktool.ToolMain**
Caused by: java.lang.ClassNotFoundException: com.imperva.apiattacktool.ToolMain

**Comment by thenorthernpole** [comment]
Hi,

Thanks for reaching out.
1. Please provide the steps you performed before running this command.
2. Try running: `java -jar imperva-api-attack-tool.jar`, what does this command output?

**Comment by alishahaan** [comment]
I have tried these steps on windows cmd 
step 1 : gradlew build --warning-mode=all 
**result= BUILD SUCCESSFUL**
step 2 : cd build/libs
step2 generates a zip file in libs folder named as: **"automatic-api-attack-tool-master.jar"**
step3 : java-jar automatic-api-attack-tool-master.jar
**Error:   Could not find or load main class com.imperva.apiattacktool.ToolMain
Caused by: java.lang.ClassNotFoundException: com.imperva.apiattacktool.ToolMain**

**Comment by thenorthernpole** [comment]
Hi,

I am not sure what you are running here exactly since the outputted jar file name convention is not by what has been defined in build.gradle. Have you changed the file? 
Which Gradle version are you using?

Thanks!

**Comment by thenorthernpole** [comment]
@alishahaan you haven't responded. My guessing is that you've found the issue?
