### ISSUE TITLE
Gradle build failure

### ISSUE THREAD

**Issue by adunkey** [imperva/automatic-api-attack-tool#3]
when building the project: I get the following:

* Where:
Build file '/apps/imperva/automatic-api-attack-tool/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating root project 'automatic-api-attack-tool'.
> Plugin with id 'findbugs' not found.

I have changed to 'spotbugs' but I get the same result.

**Comment by SecT0uch** [comment]
Same here, able to bypass the issue by commenting: 
`apply plugin: 'findbugs'` and `findbugsMain.enabled = false`

**Comment by thenorthernpole** [comment]
Please have this as a workaround for now (commenting out the findbugs plugin).
I will supply a better solution later today/tomorrow.

**Comment by thenorthernpole** [comment]
I have set up a fresh Ubuntu installation, over Windows.
Downloaded Gradle 5.2.1, with OpenJDK 1.8.0_232
Ran `gradle build`, and got no issues whatsoever (Build was successful).

Please state your Gradle version and the exact cmd steps you've performed.

**Comment by adunkey** [comment]
RHEL7 Java 1.8.0 & Gradle 6.0.1; just ran 
gradle build

Thanks

**Comment by thenorthernpole** [comment]
@adunkey have you had the chance to pull the latest changes and run the Gradle wrapper?

**Comment by adunkey** [comment]
@thenorthernpole 
just tried it there: get:
FAILURE: Build failed with an exception.

* Where:
Build file '/apps/imperva/automatic-api-attack-tool/build.gradle' line: 2

* What went wrong:
Plugin [id: 'com.github.spotbugs', version: '3.0.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.github.spotbugs:com.github.spotbugs.gradle.plugin:3.0.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository

**Comment by thenorthernpole** [comment]
Hi @adunkey,
Please run the build using the Gradle wrapper (new instructions were updated in the README).

`./gradlew build`

Thanks

**Comment by adunkey** [comment]
works! thanks!
